config/routes.rb
Rails.application.routes.draw do
  root 'charts#index'
  resources :charts do
    resources :songs
  end

  scope 'songs/:song_id', as: 'song' do
    resources :artists, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/chart.rb
class Chart < ApplicationRecord
  validates_presence_of :name
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :chart, optional: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :update, :edit, :destroy]
  def index
    @charts = Chart.all
  end

  def show
    @songs = Song.where(chart_id: @chart.id)
  end

  def new
    @chart = Chart.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @chart = Chart.new(chart_params)

    if @chart.save
      redirect_to chart_path(@chart)
    else
      render partial: "form"
    end
  end

  def update
    if @chart.update(chart_params)
      redirect_to chart_path(@chart)
    else
      render partial: "form"
    end
  end

  def destroy
    @chart.destroy
    redirect_to charts_path
  end

private

  def set_chart
    @chart = Chart.find(params[:id])
    @song = Song.all
  end

  def chart_params
      params.require(:chart).permit(:name)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :update, :edit, :destroy]
  def index
    @songs = Song.all
  end

  def show

  end

  def new
    @song = Song.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to song_path(@song)
    else
      render partial: "form"
    end
  end

  def update
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render partial: "form"
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
      params.require(:song).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/charts/_form.html.erb
<h1><%= @chart.id ? 'Edit chart' : 'Create chart' %></h1>
<hr />
<%= form_for @chart do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/charts/index.html.erb
<h1>Billboard's Greatest</h1>
<%= link_to 'Create a new chart', new_chart_path %>
<ul>
  <% @charts.each do |chart| %>
    <li>
      <%= link_to chart.name, chart %>
    </li>
  <% end %>
</ul>




<!--<p>Find me in app/views/charts/index.html.erb</p>-->

app/views/charts/show.html.erb
<h1><%= @chart.name %></h1>

<ul>
  <% @songs.each do |song| %>
  <li><%= song.name %>, <%= song.artist.name %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>